[INT-141] [INT-142] User and role management
ystv/internal-site pull request #137
Opened 2024-09-03 16:06 UTC by archessmn

Add admin pages for managing users and roles.

Features:
- Edit user roles
- Create, update and delete roles and their permissions

2024-09-03 18:20 UTC, markspolakovs reviewed
Looking good! Not done a fully exhaustive review, these are just the first things I spotted.

2024-09-03 18:20 UTC, markspolakovs commented on app/(authenticated)/(superuser)/admin/page.tsx
> +        </Link>
nitpick: `manage` is redundant
```suggestion
        <Link href={"/admin/users"}>
          <Button variant="default">Users</Button>
        </Link>
        <Link href={"/admin/positions"}>
          <Button variant="default">Crew Positions</Button>
        </Link>
        <Link href={"/admin/roles"}>
          <Button variant="default">Roles</Button>
        </Link>
```

2024-09-03 18:20 UTC, markspolakovs commented on app/(authenticated)/(superuser)/admin/roles/RoleCard.tsx
> +                    const deletedRole = await props.deleteAction({
How hard would it be to have a loading indicator (perhaps with `startTransition` to help)?

2024-09-03 18:20 UTC, markspolakovs commented on lib/search/index.ts
> +export function getTsQuery(query: string): string {
comment explaining what this does?

2024-09-03 18:20 UTC, markspolakovs commented on lib/auth/permissions.ts
> +  "Admin.Users.Admin",
I feel like we're saying `Admin` a lot :p on a serious note, this feels like it'd be covered by `ManageMembers.Members.Admin` (though that isn't a great name either)

2024-09-03 18:20 UTC, markspolakovs commented on app/(authenticated)/(superuser)/admin/users/[userID]/GiveUserRoleForm.tsx
> +                          message: `Unable to give user ${role.name} role. Please contact Computing Team`,
Given it'll most likely be comp looking at this page (which is behind a fairly advanced permissions check), could we give more detail here?

2024-09-03 18:20 UTC, markspolakovs commented on app/(authenticated)/(superuser)/admin/roles/RoleView.tsx
> +  const getSearchParams = useSearchParams();
Naming nitpick: `getXxx` implies a function that returns Xxx, how about `rawSearchParams`?

2024-09-03 18:20 UTC, markspolakovs commented on app/(authenticated)/(superuser)/admin/roles/RoleView.tsx
> +  }, [searchParamsState]);
Why not use the search params as the source of truth - would that avoid needing this effect at all?

2024-09-03 18:20 UTC, markspolakovs commented on app/(authenticated)/(superuser)/admin/roles/RoleView.tsx
> +      );
This seems like an anti-pattern (to work out what happens to the roles context I need to look across multiple files, and I imagine there might be concurrency issues here too). Could we use TanStack Query here, wrapped directly around the server action, and avoid this context machinery?

2024-09-03 18:23 UTC, archessmn commented on lib/auth/permissions.ts
> +  "Admin.Users.Admin",
Admin.Users.Manage?

2024-09-03 18:25 UTC, markspolakovs commented on lib/auth/permissions.ts
> +  "Admin.Users.Admin",
Would there ever be any non-`Manage` permissions under `Admin.Users`? If not, just `Admin.Users` might do it. (Though I'd still consider either reusing or removing the `ManageMembers` ones, otherwise it'll get confusing.)

2024-09-03 18:32 UTC, archessmn commented on lib/auth/permissions.ts
> +  "Admin.Users.Admin",
Those ManageMembers ones are only used in the `/user/x` page, which I don't think works currently for other users anyway and is made redundant, am I okay to remove the bit for fetching other users and just change that page to `/user/me` only?

2024-09-03 18:40 UTC, archessmn commented on app/(authenticated)/(superuser)/admin/roles/RoleView.tsx
> +  }, [searchParamsState]);
I'm pretty sure the reason I did it this way round in the first place was because it didn't work using the search params as the source of truth, and would delay updates so you'd end up with the state being a step behind what it should be.

2024-09-03 18:49 UTC, archessmn commented on app/(authenticated)/(superuser)/admin/roles/RoleCard.tsx
> +                    const deletedRole = await props.deleteAction({
If you mean when clicking actually adding the role, there already is one that shows up between clicking and the modal closing.

2024-09-03 18:51 UTC, archessmn commented on app/(authenticated)/(superuser)/admin/roles/RoleView.tsx
> +      );
We definitely could use TanStack Query here yep.
(I was trying to avoid that until I redo more of the data fetching but it has to be done eventually)

2024-09-03 23:55 UTC, archessmn commented on app/(authenticated)/(superuser)/admin/roles/RoleView.tsx
> +      );
This might actually have to be something I do later on as I haven't merged the PR that adds TanStack Query yet (unless you're happy for that to be merged now https://github.com/ystv/internal-site/pull/120)

2024-09-05 01:31 UTC, archessmn commented on app/(authenticated)/(superuser)/admin/roles/RoleView.tsx
> +  }, [searchParamsState]);
Oh actually I remembered why this is here, there were some cases where it would get stuck in a loop updating the search params iirc, what this does is makes sure it only pushes if they've actually changed

2024-09-19 16:27 UTC, markspolakovs requested changes
Seems like we as a codebase need to decide where action permissions checks go - the action function or the feature? My preference is for the former as it's easier to tell what permission an action needs.

Otherwise looking good, mainly just error handling.

2024-09-19 16:27 UTC, markspolakovs commented on app/(authenticated)/admin/layout.tsx
> +    return notFound();
Should we give a 403 here?

2024-09-19 16:27 UTC, markspolakovs commented on app/(authenticated)/admin/positions/PositionView.tsx
> +        throw new Error("An error occurred updating roles.");
Would ideally handle this more gracefully, but give only comp will use these pages this is fine for now.

2024-09-19 16:27 UTC, markspolakovs commented on app/(authenticated)/admin/positions/PositionView.tsx
> +  if (!positionsQuery.isSuccess) {
What about errors?

2024-09-19 16:27 UTC, markspolakovs commented on app/(authenticated)/admin/positions/actions.ts
> +  "use server";
Don't need this here if it's at the top of the file

2024-09-19 16:27 UTC, markspolakovs commented on app/(authenticated)/admin/positions/actions.ts
> +export async function createPositionAction(
Permissions check? dto for all of these - actions are directly exposed to untrusted, potentially unauthenticated user data.

2024-09-19 16:27 UTC, markspolakovs commented on app/(authenticated)/admin/roles/RoleCard.tsx
> +                        message: "Unable to delete role",
Reason?

2024-09-19 16:27 UTC, markspolakovs commented on app/(authenticated)/admin/roles/RoleCard.tsx
> +        &quot;? This action is destructive and will remove this role from all
```suggestion
        &quot;? This action cannot be undone and will remove this role from all
```

2024-09-19 16:27 UTC, markspolakovs commented on app/(authenticated)/admin/roles/RoleView.tsx
> +            description="Due to the way this search works, only one permission can be searched at a time."
```suggestion
            description="Only one permission can be searched at a time."
```

2024-09-19 16:27 UTC, markspolakovs commented on app/(authenticated)/admin/roles/actions.ts
> +  "use server";
Same note above about the `"use server"`s and permissions checks

2024-09-19 16:27 UTC, markspolakovs commented on app/(authenticated)/admin/roles/layout.tsx
> +    return <p>No permissions sorry</p>;
lol

2024-09-19 16:27 UTC, markspolakovs commented on app/(authenticated)/admin/roles/page.tsx
> +    return <>An error occurred</>;
logging / details would be good

2024-09-19 16:27 UTC, markspolakovs commented on app/(authenticated)/admin/users/UserView.tsx
> +        throw new Error("An error occurred updating roles.");
reason?

2024-09-19 16:27 UTC, markspolakovs commented on app/(authenticated)/admin/users/UserView.tsx
> +            description="Search must start of the first, last or nick name, or username."
```suggestion
            description="Search must start with the first, last, or nick name."
```

(rip usernames 2023-2024)

2024-09-19 16:27 UTC, markspolakovs commented on app/(authenticated)/admin/users/[userID]/AdminUserView.tsx
> +                                    message: `Failed to remove user from ${role.name} role.`,
reason?

2024-09-19 16:27 UTC, markspolakovs commented on features/people/roles.ts
> +  "use server";
Why are these `use server`'d?

2024-09-23 13:09 UTC, archessmn commented
> Seems like we as a codebase need to decide where action permissions checks go - the action function or the feature? My preference is for the former as it's easier to tell what permission an action needs.

Having the permissions checks in the features makes sure that checks aren't forgotten when implementing those features in the future, some features are also passed directly from server components without an action wrapper and so the checks are required in the feature.

2024-10-01 10:27 UTC, merged