[INT-201] #CheckWithTech enhancements
ystv/internal-site pull request #168
Opened 2024-10-07 20:27 UTC by markspolakovs

- Stores the state of requests in the database, and displays on events to techies
- Full Slack integration
  - Techies can action requests from within Slack
  - Requestors are notified of the status

TODO:

- [ ] We should probably warn if the requester isn't signed in to Slack so the approver lets them know some other way
- [ ] An admin UI to list pending CWTs

2024-10-07 20:33 UTC, markspolakovs commented on features/calendar/events.ts
> +// import "server-only";
```suggestion
import "server-only";
```

2024-10-07 20:34 UTC, markspolakovs commented on lib/env.ts
> +  SLACK_CHECK_WITH_TECH_CHANNEL: slackEnvType,
ACHTUNG: there's some places that the slack API requires a channel ID, so I remove the default here. We need to make sure the ID is set in ystv/nomad prior to merging.

2024-10-07 21:45 UTC, markspolakovs commented on lib/env.ts
> +  SLACK_CHECK_WITH_TECH_CHANNEL: slackEnvType,
Done.

2024-10-08 10:45 UTC, archessmn requested changes
Would be good to have these bits changed as well as having the "need help" flow use it as well.

I've made a few UI changes but otherwise looks good.

2024-10-08 10:45 UTC, archessmn commented on features/calendar/check_with_tech_actions.ts
> +    await respond({
Can we have this message only show for the user that clicked it?

2024-10-08 10:45 UTC, archessmn commented on features/calendar/check_with_tech_actions.ts
> +    await respond({
Same with only showing to the single user

2024-10-08 17:53 UTC, markspolakovs commented on features/calendar/check_with_tech_actions.ts
> +    await respond({
Fairly sure that this should be an ephemeral message, per https://api.slack.com/interactivity/handling#publishing_ephemeral_response

2024-10-08 18:14 UTC, archessmn commented on features/calendar/check_with_tech_actions.ts
> +    await respond({
I thought that's what it was but couldn't remember if it was something different for slack

2024-10-08 18:35 UTC, markspolakovs commented on features/calendar/check_with_tech_actions.ts
> +    await respond({
Same response

2024-10-08 20:39 UTC, markspolakovs commented
<img width="1278" alt="image" src="https://github.com/user-attachments/assets/51c91fcb-abf9-43fb-9187-a6546e7bdcd9">

2024-10-08 20:45 UTC, markspolakovs commented on docs/setup_slack.md
> +- `SLACK_TECH_HELP_CHANNEL` - Used for help with tech requests
```suggestion
```
rip

2024-10-09 14:45 UTC, archessmn commented on features/calendar/check_with_tech_actions.ts
> +    await respond({
I've got two accounts on my dev instance and can see the messages on both

2024-10-09 15:01 UTC, archessmn commented
![image](https://github.com/user-attachments/assets/b64d30a8-9699-473a-87cf-459d4ecb4691)
Needs spacing fixing

2024-10-09 16:24 UTC, archessmn approved these changes

2024-10-09 17:32 UTC, markspolakovs commented on lib/auth/permissions.ts
> +  "CheckWithTech.Submit",
And doesn't show the prompt at all - essentially intended as a feature flag.

2024-10-09 17:59 UTC, merged